#---------------------------------------------------------
################# General Aspects section ################
#---------------------------------------------------------
  
name: CECALT - CEnter of MeteorologiCAL Technology
description: CECALT is an integral solution which contributes to hurricane prediction sensitivity.
author:  Aaron Castillo, Javier Sanchez, Gilberto Subias.
specification_version: 1.0
prototype_version: 1.0

#---------------------------------------------------------
############## Environment variables section #############
#---------------------------------------------------------

environment_variables:
  OPERATING_SYSTEM_PATH:
    default: "/home/cdsw/"
    description: "The full path needed to read all necessary files and variables"

  USE_PREBUILT_MODEL: 
    default: "yes"
    description: "Specifying the usage of a prebuilt model"

  ETL_OPERATIONS: 
    default: "no"
    description: "Specifying if a ETL operation takes place and therefore, getting an updated input"
    
#---------------------------------------------------------
##################### Runtime section ####################
#---------------------------------------------------------

runtimes:
  - editor: Workbench ## Other acceptable values are determined by the runtimes available in your CML environment
    kernel: Python 3.9 ## Same here, check your runtimes (custom runtimes can be added as well)
    edition: Standard ## Particularly relevant if using GPUs, Nvidia GPU

## Below are some sample tasks based on some of the most popular aspects of AMP creation.
tasks:

  #---------------------------------------------------------
  #################### Session section #####################
  #---------------------------------------------------------
  
  - type: run_session
    name: Install Dependencies
    script: scripts/01_install_dependencies.py
    short_summary: Install requirements and dependencies
    kernel: python3
    cpu: 2
    memory: 4
    
  #---------------------------------------------------------
  ########### Extract, Transform and Load section ##########
  #---------------------------------------------------------

  - type: create_job
    name: Hurricane ETL
    entity_label: etl_execution
    script: scripts/022_transform_and_load_data.py
    arguments: None
    short_summary: Job to apply the ETL process.
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: etl_execution
    cpu: 2
    memory: 4
    short_summary: Run ETL job.
    long_summary: >-
      Running the job to apply the ETL process.

  #---------------------------------------------------------
  ###### Feature Engineering and Traing Model section ######
  #---------------------------------------------------------

  - type: create_job
    name: Train hurricane prediction model
    entity_label: train_model
    script: scripts/04_train_model.py
    arguments: None
    short_summary: Job to train model.
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: train_model
    cpu: 2
    memory: 4
    short_summary: Run model training job.
    long_summary: >-
      Running the job to train models.
      
  #---------------------------------------------------------
  ############ Create, Build and Deploy sections ###########
  #---------------------------------------------------------
  #Note: all create, build and deploy must be implemented or removed completely together.


      
  #---------------------------------------------------------
  ################### Application section ##################
  #---------------------------------------------------------
  
  #- type: start_application
  #  name: CECALT Application
  #  short_summary: CECALT implementation for wind speed prediction. 
  #  subdomain: hurricane-prediction
  #  script: scripts/06_launch_app.py
  #  environment_variables:
  #   TASK_TYPE: START_APPLICATION
